apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: symfony  # Changez en fonction du namespace que vous souhaitez utiliser
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: docker.io/abdelbagui/symfony_app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-docker-secret

